# Generated by Django 4.2.13 on 2024-07-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_region_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='historia2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='textoAgregado',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
