# Generated by Django 4.2.13 on 2024-06-10 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_id_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('nom_usuario', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_postal', models.IntegerField()),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='alumnos.genero')),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
