# Generated by Django 4.2.13 on 2024-06-12 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_usuario_delete_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id_profesion', models.AutoField(db_column='iProfesion', primary_key=True, serialize=False)),
                ('profesion', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_genero',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_profesion',
            field=models.ForeignKey(db_column='idProfesion', default=1, on_delete=django.db.models.deletion.CASCADE, to='alumnos.profesion'),
            preserve_default=False,
        ),
    ]
