# Generated by Django 4.2.13 on 2024-06-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_profesion_remove_usuario_id_genero_delete_genero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_alumno',
            new_name='id_usuario',
        ),
    ]
