# Generated by Django 4.2.13 on 2024-07-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_noticia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoNoticia',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
