# Generated by Django 4.2.13 on 2024-06-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_rename_id_alumno_usuario_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
