# Generated by Django 4.2.13 on 2024-06-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_categoria_tipo_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Users',
        ),
    ]
